sonar.projectName=carshop-backend
sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=src/**/*.spec.ts,src/**/*.test.ts,test/**/*.spec.ts,test/**/*.test.ts
sonar.exclusions=dist/**,node_modules/**,coverage/**,src/main.ts,src/**/*.d.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
